### ISSUE TITLE
Animal Release Date: Min Age Requirement

### ISSUE THREAD

**Issue by leigharobinson** [nss-cohort-40/c40-keahua-arboretum-hula_dancers#26]
Build a function that doesn't allow an animal to be released into the wild before their recommended release age: 

- [x] Pueo MINIMUM RELEASE AGE 8 months
- [x] River Dolphins MINIMUM RELEASE AGE 13 months
- [x] 'Ulae MINIMUM RELEASE AGE 1 months
- [x] Gold Dust Day Gecko MINIMUM RELEASE AGE 2 months
- [x] Nene Goose MINIMUM RELEASE AGE 7 months
- [x] Kikakapu MINIMUM RELEASE AGE 1 months
- [x] Ope'ape'a MINIMUM RELEASE AGE 5 months
- [x] Hawaiian Happy-Face Spider MINIMUM RELEASE AGE 0.5 months

In the release_animal.py file add the functions that req the age input and checks to see if the age meets min requirement.

**Comment by sarahholder** [comment]
```
    if choice == "1":
        animal = RiverDolphin()
        animal_age_in_months = input("Enter animal age in months > ") 
        animal_age_int = int(animal_age_in_months)
        if animal_age_int < animal.minimum_age_in_months:
            print("\n\nAnimal is too young to be released. Please choose a older animal.")
            input("\n\nPress any key to continue...")
            release_animal(arboretum)
            #return to release_animal menu
        else:
            rivers_and_swamps = arboretum.rivers + arboretum.swamps
            for index, river_swamp in enumerate(rivers_and_swamps):
                print(f'{index + 1}. River/Swamp: {river_swamp.name} - {river_swamp.id}')
            print("Release the animal into which biome?")
            choice = input("> ")
            rivers_and_swamps[int(choice) - 1].animals.append(animal)
